### ISSUE TITLE
SSH key required during push, even w/ Pantheon token auth

### ISSUE THREAD

**Issue by davisshaver** [pantheon-systems/terminus-build-tools-plugin#122]
Long time, first time... appreciate all the Pantheon tooling work...

I've run into a bug with my new deployment script on Circle CI (version 2 infrastructure). I get prompted for my SSH key after the following:

```
$HOME/project/vendor/bin/terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

case "$CIRCLE_BRANCH" in
  master )
    $HOME/project/vendor/bin/terminus -n build:env:push "$TERMINUS_SITE.dev" --yes ;;
  test )
    $HOME/project/vendor/bin/terminus -n build:env:push "$TERMINUS_SITE.test" --yes ;;
  live )
    $HOME/project/vendor/bin/terminus -n build:env:push "$TERMINUS_SITE.live" --yes ;;
esac
```

Here's a screenshot of the CircleCI output:
<img width="1324" alt="screen shot 2017-12-20 at 2 58 42 pm" src="https://user-images.githubusercontent.com/1636964/34226007-53e1641a-e596-11e7-8007-594e4d4c4bd8.png">

**Comment by greg-1-anderson** [comment]
1. Why are you using `build:env:push`?
1. Why are you pushing to the dev branch instead of a multidev? If you push to a multidev, you should use `build:env:create`. This will revert to doing just a push if the multidev already exists.
1. You cannot push to test and live; you can only deploy to test and live. You should use the normal Pantheon workflow to deploy rather than building in Circle.
1. `terminus auth:login` authenticates for all Terminus commands that go through the Hermes API, which is most commands, save for those that use ssh, e.g. `terminus drush`, `terminus wp`, `terminus drupal` etc., which use ssh key authentication. Git operations also use ssh key authentication. The message you are seeing indicates that you have not set up an ssh key with CircleCI to allow the push to happen.

In any event, your use case is not supported by the Build Tools plugin. Please create a new site following the documentation: https://pantheon.io/docs/guides/build-tools/. Note that running the `terminus build:project:create` command will automatically set up ssh key authentication for you.

Once you have the basic workflow functioning correctly, you may then experiment with customizing it for more advanced workflows.

**Comment by davisshaver** [comment]
Not sure I agree with closing, as I have been trying to follow the docs closely. If it were my project and you were my user, I'd chalk the errors to poor documentation. But of course that isn't the case, and it seems you are quite confident that this was a closable issue.... 

Perhaps these multidev characteristics wouldn't be familiar to me, as though I have been a paying customer for a few years now, my plan does not support multidev.

I am reviewing your comments more closely now and appreciate you shooing me out of your repo as quickly as possible :)

**Comment by davisshaver** [comment]
@greg-1-anderson I have left a comment in the Pantheon Power Users Slack registering my frustration with this exchange... https://pantheon-community.slack.com/archives/C2GJ3JG7Q/p1513803920000013

**Comment by davisshaver** [comment]
Now to get back to substance!

As you noted, "your use case is not supported by the Build Tools plugin." I would like to understand this!

To help us be on same page, my use case is making a repo "fat" and pushing to Pantheon's `dev` environment. The CircleCI job being discussed here would only be run on the `master` branch, thereby ensuring that `master === dev` at all times.

It's not clear to me what you are recommending as resolution, unless the guidance is truly that I'm in the wrong place, which would seem... odd.

I am grateful to hear your feedback that pushing to `test` or `live` doesn't make sense. I thought that might be the case. Coming from big agency world I see value in environment-specific branches. Perhaps a Pantheon git push back? But yeah, maybe just a bad idea.

**Comment by jsiragusa** [comment]
I know this is an old thread, but for what it's worth I was having the same issue with `build:env:push` and solved it by adding an SSH key (https://pantheon.io/docs/ssh-keys/) to Pantheon and then adding that key in CircleCI (https://circleci.com/docs/2.0/add-ssh-key/)
