### ISSUE TITLE
2.0.0-beta1 isn't removing my ci- environments

### ISSUE THREAD

**Issue by nterbogt** [pantheon-systems/terminus-build-tools-plugin#155]
terminus build:env:delete "my-site" --keep=2
 [notice] Nothing to delete. Keeping ci-729,ci-732,ci-738,ci-739,ci-743,ci-745,ci-749,ci-752,ci-754.

**Comment by philltran** [comment]
I think the issue is that  `$environmentsWithoutPRs`  is an empty array in [src/Commands/EnvDeleteCommand.php](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/6c6507b03e3c3715035dd68b10dfdc2b3a1fc46d/src/Commands/EnvDeleteCommand.php#L173) line 173

[`        $oldestEnvironments = $environmentsWithoutPRs;`](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/6c6507b03e3c3715035dd68b10dfdc2b3a1fc46d/src/Commands/EnvDeleteCommand.php#L173)

I think ` $oldestEnvironments = $environmentsWithoutPRs;` should be in the previous else if statement.

**Comment by philltran** [comment]
I think this is related to #128 
The function `preserveEnvsWithOpenPRs` is not returning the correct list of env

**Comment by philltran** [comment]
It looks like the `filterBranches` function is comparing the env name stripped of "ci-" to the start of git branch names. The build tool is creating pantheon environments named "ci-[circle build #". So `filterBranches` returns an empty array. 

I see a TODO comment suggesting fetching the correct branch name from 'build-metadata.json'.

**Comment by philltran** [comment]
I submitted PR #167 . Can someone please review and test that it works for them? Thanks.

**Comment by greg-1-anderson** [comment]
Please try with Build Tools 2.0.0-beta5 (n.b. requires Terminus 2). You can get this in CircleCI by using `- image: quay.io/pantheon-public/build-tools-ci:4.x` in your .circleci/config.yml.

**Comment by ataylorme** [comment]
Closing this out due to inactivity. If the issue persists, please re-open or create a new issue

**Comment by ataylorme** [comment]
#171 resolved this but you will need to update your Terminus Build Tools version. You can use `quay.io/pantheon-public/build-tools-ci:6.x`
