### ISSUE TITLE
Private git repository in composer

### ISSUE THREAD

**Issue by Nikro** [pantheon-systems/terminus-build-tools-plugin#204]
Hi there,

I want to specify some private repositories (for custom modules or for custom themes) within `composer.json` - but I need somehow to set deployment keys from within Pantheon environments. Is there a way to know which pantheon keys will be used on every CI environment?

I've added deployment key between my private theme repo <-> CircleCi - but still runs generates error:

```
  [RuntimeException]                                                                                                       
  Failed to clone https://github.com/org/lorem-ipsum.git via https, ssh protocols, aborting. 
```

Probably I'm missing something. Thanks.

**Comment by ataylorme** [comment]
Hi @Nikro since CircleCI is downloading the Composer dependencies and deploying the result to Pantheon you don't need to authenticate in the Pantheon environment.

Composer will, however, need to authenticate with your private repositories. See [the Composer documentation on using private VCS sources](https://getcomposer.org/doc/05-repositories.md#using-private-repositories). 

> The only requirement is the installation of SSH keys for a git client.

You will need an additional SSH key(s) added to CircleCI that have permissions to access the private repositories in addition to adding the `vcs` entries in the `repositories` section of `composer.json`
