### ISSUE TITLE
build:project:create wp workflow loads drupal docker image

### ISSUE THREAD

**Issue by pdcodes** [pantheon-systems/terminus-build-tools-plugin#210]
When creating a WP site using the terminus build tools plugin, the .circleci config uses a drupaldocker image (drupaldocker/php:7.1-cli) instead of the proper image for a WP site.

Steps to reproduce:

1. Run `terminus build:project:create wp ...`
2. Review config.yml file in /.circleci
3. Verify docker/image attr's

**Comment by ataylorme** [comment]
So the `drupaldocker` image [only shows up in the `1.0.1` tag](https://github.com/pantheon-systems/example-wordpress-composer/blob/1.0.1/.circleci/config.yml#L4).

The `master` branch has quite a few updates since then.

@greg-1-anderson I'd like your opinion on whether we should

1) Tag a new version of `example-wordpress-composer` and `example-drops-8-composer` and establish a cadence for new releases going forward
or
2) Update Build Tools to pull from the `master` branch of those examples

I am leaning towards the second option as all changes to `master` have PRs and tests.

**Comment by ataylorme** [comment]
In the short term I created [a `2.0` release of `example-wordpress-composer`](https://github.com/pantheon-systems/example-wordpress-composer/releases/tag/2.0.0) as the last release was in November 2017.

In the long term:

I think it is a philosophical difference in starter vs framework. I would agree on continuing to use stable tags if the example repos were a framework, but they are not.

I don’t see a reason folks shouldn’t get the latest `dev-master` for their starting point, regardless when we hade the last release.

All PRs to `master` on those repos have code reviews, tests, etc. We aren’t merging test/unstable code into `master`.

If we use `dev-master` for `composer-create-project` then we should either only do it for the Pantheon maintained starters (`d8`, `d7`, `wp`) or make it the default and add a `--prefer-stable` for those using custom starting repos who want to start from stable tags.

**Comment by ataylorme** [comment]
I'm closing this out as new project made with `terminus build:project:create wp` will use the `2.0` release tag
