### ISSUE TITLE
Explore support for Github Actions

### ISSUE THREAD

**Issue by nerdstein** [pantheon-systems/terminus-build-tools-plugin#230]
This is a new feature from Github.

https://github.com/features/actions

It would be great if this build tool plugin could be integrated.

**Comment by ataylorme** [comment]
Hi @nerdstein,
Thanks for the suggestion. I did some exploration and while GitHub actions are very cool they are lacking the ability to configure items like SSH keys and environment variables through an API.

This is a requirement of CI providers Build Tools supports as part of the magic of `build:project:create` is doing those steps automatically, rather than having to do them manually for each project.

While you certainly can use GitHub actions with Pantheon, until there is API access to configure GitHub Actions it isn't a fit for Build Tools.

**Comment by davereid-pfg** [comment]
Maybe this could be reconsidered now that the above have been addressed in Github Actions?

**Comment by greg-1-anderson** [comment]
Sounds like an excellent suggestion.

**Comment by sugaroverflow** [comment]
Closing in lieu of duplicate #350 and work is currently being done on this 😄 so please take the discussion there. Thank you!
