### ISSUE TITLE
A customer Transferred their GitHub repo under their organization and the build setup got broken

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/terminus-build-tools-plugin#252]
A customer reported that they transferred their GitHub repo under their organization and the build setup got broken, what is the best way for them to get it under an org and make it still working? If not possible to get a repo under an org, how can they put it back and be associated with their build workflow?

**Comment by ataylorme** [comment]
CircleCI should take care of that automatically as it mirrors GitHub with permissions. Sometimes it can take a little while to update. I would give it a day or so and if things are still not working open a support ticket with Circle CI

**Comment by carl-alberto** [comment]
Thanks for the quick reply @ataylorme. They will try to post back in this thread if they will encounter further issues

**Comment by ataylorme** [comment]
Another alternative is to create a new build
tools project with the correct organization association and then copy the code to the new GitHub repo and move the DB and files from the existing site

**Comment by greg-1-anderson** [comment]
I'm not sure that everything auto-updates after an org change, but it's been a while since I've been through this; maybe things have improved.

We have the `build:project:repair` command, which re-applies all of the authentication credentials on an existing site.

The other issue you may have is that the build metadata might prevent multidevs from auto-deleting once their PR is closed. Manually delete all of your multidevs (on the dashboard or via Terminus), and new metadata will be written for each multidev created thereafter.

**Comment by ataylorme** [comment]
@carl-alberto did this get resolved?

**Comment by ataylorme** [comment]
I'm going to close this out. Please re-open if there are further developments
