### ISSUE TITLE
Question: Why "Empty WordPress" Upstream by default in Pantheon?

### ISSUE THREAD

**Issue by nelsonamaya82** [pantheon-systems/terminus-build-tools-plugin#295]
Question: Why the `terminus build:project:create` command creates the site in Pantheon with "Empty WordPress" Upstream by default? Where can I change it to be just "WordPress"?

Thanks.

**Comment by ataylorme** [comment]
@nelsonamaya82 this is intentional as WordPress is being managed with Composer on the external GitHub repository. As part of this workflow, you are giving up the "one-click" WordPress core updates in the Pantheon dashboard. You should *not* change it back to the normal WordPress upstream. See [`pantheon.io/docs/composer`](https://pantheon.io/docs/composer) for more details
