### ISSUE TITLE
GitLab branchesForPullRequests does not handled "closed" state properly

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#297]
[`branchesForPullRequests` in `GitLabProvider.php` line `194`](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/7791475ecfa24aca55b434d174c2901385d916a7/src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php#L194) `implode`s the array `['merged', 'closed']` without a separator and passes that as the `state` value to the GitLab API.

The GitLab API can only accept one state at a time. Two API calls should be made here and the results merged.

See https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

**Comment by rvtraveller** [comment]
Looking into this, this hasn't come up before because the only place that uses this method is the MultiDevRetention class (https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Utility/MultiDevRetention.php#L103) and it retrieves all pull/merge requests (in the "all" state).

Should have a change here momentarily that I tested...but I had to write a custom command to expose the data since we weren't using the other options anywhere.
