### ISSUE TITLE
Add option for Drupal 9

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#336]
I'm working on plans for rolling on Drupal 9 support. While we don't yet have an example repository for Build Tools to copy, once we do, we should update this list: https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/52cc3ee9ed0c3e9765d3c29a67fa07bea2c2e28a/src/Commands/BuildToolsBase.php#L322

**Comment by greg-1-anderson** [comment]
So the interesting thing is that once Drupal 9 is released, `drops-8` will become Drupal 9. This is odd, but the alternative would be to make all Dashboard-updated Drupal sites jump through hoops to get to Drupal 9.

We could add a "d9" alias that points to a pre-release Drupal 9, and then change the alias to drops-8 once Drupal 9 ships.

**Comment by danshumaker** [comment]
@greg-1-anderson When you say "once Drupal 9 ships" -- but It was released June 3. 
 https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means ..   I don't mean to be pushy.. I'm just looking for a quick docksal/pantheon/drupal9 spin up script and was a little surprised that terminus/pantheon  didn't have it yet.   I'll blame it on Covid.  :)

**Comment by greg-1-anderson** [comment]
Due to shifting priorities, Drupal 9 currently is only supported on Composer-managed sites. At the moment, it looks like drops-8 will remain Drupal 8 only. Today, if you want to run Drupal 9 on Pantheon, you must start with a new Composer-managed site using Integrated Composer. Follow the [Drupal 9](https://pantheon.io/docs/drupal-9) docs.

In the future, the hoops may be removed, and a migration path from Drupal 8 drops-8 sites to Drupal 9 IC sites on the dashboard may be provided; however, this is presently TBD.

It is possible to use Drupal 9 with build tools today; however, today, the only way to get the new version of MariaDB on Pantheon is to start a new Drupal 9 site. All other sites will continue to run on the older version of MariaDB until the new version has rolled out to the rest of the platform. I don't have an ETA on that. The upshot is that if you want to use Drupal 9 with build tools, you'll have to add the patch that removes the MariaDB version checks, and accept the risk, or perhaps use the [mysql 5.6 module](https://www.drupal.org/project/mysql56/issues/3167170).

**Comment by danshumaker** [comment]
Thank you very much @greg-1-anderson !  It (your link) worked great  ( https://dashboard.pantheon.io/sites/create?upstream_id=e96c6794-77fe-4931-9a20-48a2fe1a3789  ) .  Exactly what I needed.  If I have more time, I'll dig more into total automation to see if I can do all that Browser UI stuff with terminus only.  Cheers!

**Comment by rvtraveller** [comment]
While not integrated into Build Tools yet, you can still create a Drupal 9 site using Terminus itself.

`terminus site:create --org=<org> --region=<region> -- <site name> <site label> e96c6794-77fe-4931-9a20-48a2fe1a3789`

Just be sure to use that UUID for the upstream in your command.

**Comment by greg-1-anderson** [comment]
n.b. If you follow those instructions you will be running on Mariadb 10.0.

**Comment by greg-1-anderson** [comment]
c.f. https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/368

**Comment by kporras07** [comment]
This was added recently in https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/396 so I think this can be closed now. Feel free to reopen if further discussion is needed
