### ISSUE TITLE
change default branch to 'main'

### ISSUE THREAD

**Issue by sugaroverflow** [pantheon-systems/terminus-build-tools-plugin#347]
context: https://twitter.com/mislav/status/1270388510684598272

possibly using https://gist.github.com/PurpleBooth/6983e5c4def4f8721d4a697a3f4606a7#file-change-github-default-branch-sh

**Comment by greg-1-anderson** [comment]
For just one repository, the easy way to do it is to push a new branch e.g. "main" and then change the default branch from "Settings".

For a project like the Terminus Build Tools Plugin, there is also a question as to whether any external project is depending on a branch named master existing. The conservative approach would be to mirror "main" and "master" for a while, and then delete "master". For the most part, though, this plugin should be installed via a tag, e.g. as is done in [docker-build-tools-ci](https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/Dockerfile#L87)

The script is useful if you are going to do a bunch of repositories, though.

**Comment by greg-1-anderson** [comment]
Another interesting question is, what [references are there to master](https://github.com/pantheon-systems/terminus-build-tools-plugin/search?q=master&unscoped_q=master) in the code itself? It is common for the CI for a project to have some configuration that says "build only on the master branch", and things of that nature. This plugin is a very special case, though, as it sets up _other repositories_, and there are assumptions in the code that the template repositories have a master branch, and that the repositories that we are creating will use master as the default branch. We can't change that at this time, because Pantheon has a bug that prevents any branch name other than master from being used as an upstream.

For now, we should focus on changing just the default branch for this repo and references to master that are for this repo, and carefully leave others as-is.

**Comment by sugaroverflow** [comment]
This was taken care of so closing.
