### ISSUE TITLE
Allow installing a specific profile

### ISSUE THREAD

**Issue by e0ipso** [pantheon-systems/terminus-build-tools-plugin#43]
It seems that the template does not allow to specify a profile different from the default one (_standard_).

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/86aeaa846b9438163a0282ff7e47ef0d93a5af54/src/Commands/BuildToolsBase.php#L616

It would be great to allow selecting the profile.

**Comment by greg-1-anderson** [comment]
The line you are interested is a couple up:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/86aeaa846b9438163a0282ff7e47ef0d93a5af54/src/Commands/BuildToolsBase.php#L613

For an example of this in action:

https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L79

and

https://github.com/pantheon-systems/example-drops-8-composer/blob/master/web/sites/default/settings.php#L40

(You're going to have to pretend those lines say something other than 'standard', because I haven't updated https://github.com/pantheon-systems/example-drops-8-composer/pull/33 in a while.)

If you describe your profile in your template project in those two places, then it will be used.

Having a single template projects that contains multiple profiles is not supported. Make one template project per profile.
