### ISSUE TITLE
UX: Store tokens in cache

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/terminus-build-tools-plugin#50]
I believe we should have the plugin store any third-party tokens/keys somewhere in `~/.terminus/cache` the same way that Terminus stores Pantheon machine tokens.

This will improve the UX for people getting started, as well as those who want to use the plugin on an ongoing basis.

This will also provide a better foundation for further innovation in integration w/external repos and CI services.

**Comment by ataylorme** [comment]
@joshkoenig it would be great if there was a command to save/update tokens to cache without actually scaffolding a new site as well.

This would be great for enablements so users can store their tokens ahead of time rather than potentially showing then on a screen share during a training.

**Comment by greg-1-anderson** [comment]
Partial workaround:
```
export GITHUB_TOKEN='...'
export CIRCLE_TOKEN='...'
```

**Comment by greg-1-anderson** [comment]
Started to tackle this in 4ead1ea

**Comment by greg-1-anderson** [comment]
The `master` branch now caches tokens in the Terminus cache directory. It deliberately uses the directory that is deleted by `terminus self:cc` so that there can be a way to erase your tokens. It might make sense for the credentials to be stored in the same directory as the Terminus auth tokens, but as far as I know, there is no Terminus command to flush those.

The credentials are cached in a filename that contains the name of the Terminus user you authenticated as, so your credentials won't get crossed if you occasionally authenticate as different users.
