### ISSUE TITLE
Sterile artifact build environment

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/terminus-build-tools-plugin#6]
Currently, the build tools default to building a deploy artifact using the initial git repository and working directory.

For better separation of development code, tools, and test infrastructure from the production artifact, I think it would be wise to assume a 'sterile' working directory for the build artifact that is devoid of the contents of the development repository. This can be accomplished by cloning the Pantheon repo into a preset target destination and explicitly cleaning that directory and building our deploy artifact there.

When building CI workflows in the past, I found it helpful to have this separation, especially for locally testing the build step before pushing to the CI environment, keeping the number of builds required to get the first pass down to a minimum.

What do you think @greg-1-anderson @stevector ?

**Comment by greg-1-anderson** [comment]
I don't agree with this idea. The build tools plugin should not be responsible for cloning the template repository. The initial state of your run is as sterile as you make it. Clone the repo you want, change your working directory to it, and run the tool. This should give you the starting environment you desire.

If it would make your life easier, I could certainly entertain the idea of an option that would specify the build directory, rather than assuming `getcwd()`.

**Comment by dustinleblanc** [comment]
Fair game. My concern isn't my own ease as I've built it from scratch before, but rather what is intuitive for the widest user base. This ties directly into our conversation yesterday, I'll keep trying to see if I can better understand how to make it work in the current method. Thanks for the feedback!

**Comment by greg-1-anderson** [comment]
I think "most intuitive" is, your CI service checks out your git repository, sets your cwd, and then you just call `build-env:create` from your build script.
