### ISSUE TITLE
CircleCI badge shows green/pass even though workflows are failing

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#97]
I hope to have time to investigate later today but I at least wanted to get this problem recorded.

The status badge on this repo seems to report green because the most recent job to be completed on the master branch was a pass.
https://circleci.com/gh/pantheon-systems/terminus-build-tools-plugin/tree/master

But the job is in a workflow that is failing.
https://circleci.com/gh/pantheon-systems/workflows/terminus-build-tools-plugin/tree/master

**Comment by greg-1-anderson** [comment]
That's interesting. This looks like a Circle 2.0 design bug vis-a-vis how GitHub status is reported. We could report it to them, but I'm not sure what they'd do about it. Maybe there's an easy fix; I'm not sure.

There have been a lot of false failures in the CI builds lately. I [made a report with CircleCI](	https://discuss.circleci.com/t/cant-tell-why-my-build-is-re-starting/15650
) about one situation, although most of the failures are due to intermittent Terminus failures.

**Comment by stevector** [comment]
Found a report and added a comment: https://discuss.circleci.com/t/workflow-status-badge-and-e-mail-support/14818/4

**Comment by greg-1-anderson** [comment]
Thanks!

**Comment by stevector** [comment]
The newer comments in that thread say that the issue is now fixed. @greg-1-anderson, I think we can close, do you agree?

**Comment by ataylorme** [comment]
Cleaning up old issues. This was a CircleCI issue, not a build tools issue
